name: Deploy to neocities
#Builds the site with 11ty and deploys to Neocities

# only run on changes to main
on:
  push:
    branches:
      - main

jobs:
  build: # run 11ty
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mcfitzgerald/action-build-eleventy@master
      with:
        API_KEY: ${{ secrets.LASTFM_KEY }}
        USERNAME: ${{ secrets.LASTFM_USER }}
          
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
        dist_dir: public
